### ISSUE TITLE
Partial Messages, Need for length headers ?

### ISSUE THREAD

**Issue by crakama** [kabutz/Transmogrifier#1]
How does the server take care of partial messages sent by the client since buffers are of limited size? We know that NIO uses Bytebuffer for reading and writing, we can not tell for sure that data received is indeed all that was sent or the data read from the buffer and written to the channel is indeed all. How do you ascertain that? Do we need some kind of length header?

**Comment by kabutz** [comment]
It would simply send multiple messages.  Try it out - send a long String and you'll see that it works :)
